### ISSUE TITLE
Landing Page First Look

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#1]
## Value Proposition

As a user
I want to save a word and its translation in a list
so that I can look it up again in the future
​

## Description

<img width="309" alt="Screenshot 2023-01-19 at 3 31 07 PM" src="https://user-images.githubusercontent.com/118136613/213468890-65ed3423-2535-457e-98c1-f5fa36bd0c25.png">

​

## Acceptance Criteria

- [ ] two input fields are displayed
- [ ] a submit button submits the Form 
- [ ] after submitting an entry with the word and its translation is displayed
      ​

## Tasks

- [ ] create a Landing page with a header
- [ ] create a form with two input fields and a submit-button
- [ ] write a handleSubmit function which renders an list-entry
​

## Complexity

S

**Comment by Long-HaHoang** [comment]
I just realized, that you have a navbar, but I think it's better to remove it in this user story.
My reason is: The navbar doesn't have function, yet. And you don't have multiple pages, yet.

Furthermore, you can add the title header to your acceptance criteria.

Additionally you added a empty code block below your second task.

**Comment by doemser** [comment]
I would suggest to cut the user-story smaller and only in a second step connect the API and let it recognize the language. 

In the first step, provide your user with a form where they can manually enter and save the word in both languages, just for the first iteration.

Also what @Long-HaHoang said about the navbar is important, we should never have something that doesn't work yet.

**Comment by ThomasF85** [comment]
Looks good to me!
One optional improvement: We want to name a real user benefit in the value proposition and "so that I have an entry in a list" is not a real benefit. You could write something like:
"As a user
I want to save a word and its translation in a list
so that I can look it up again in the future"
Please feel free to start working on your story and optionally editing the value proposition.
