### ISSUE TITLE
Edit Function

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#11]
## Value Proposition

**As a** User  
**I want to** edit my word entries,
**so that** I can update my entries
​

## Description

<img width="729" alt="Screenshot 2023-01-26 at 2 07 16 PM" src="https://user-images.githubusercontent.com/118136613/214843054-3d5dc328-391f-4153-97e1-9abcecb0d2bb.png">

## Acceptance Criteria

- [ ] an edit-button is displayed for each word entry 
- [ ] clicking the button opens a form where the user can edit the entry
- [ ] the form is prefilled with the current entry text in the corresponding input fields
- [ ] a backlink cancels the edit process and leads to the words page 
- [ ] submitting the form applies the changes 
- [ ] after editing the entry, the user is redirected to the words page
      ​

## Tasks

- [ ] create an edit button and a back link
- [ ] the edit form reuses the form component from the homepage (add form)
- [ ] update the form component so that the current data of the entry is already displayed as default values
- [ ] update the form component to expect props like onSubmit, titleText, labelText, submitButtonText ...
- [ ] write a handleSubmit function to update the edited entry
 
      ​

## Complexity
M

**Comment by Mistake91** [comment]
Hey Astrid, for me your US looks well thought out, hope everything will work fine for you :)

**Comment by AstridOttmann** [comment]
Thank you! Same to you :-)
