### ISSUE TITLE
IsFavorite-Function

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#12]
## Value Proposition

**As a** User
**I want to** like words and collect them in a list
**so that** I can browse through them later on  
​

## Description

<img width="621" alt="Screenshot 2023-01-26 at 3 32 26 PM" src="https://user-images.githubusercontent.com/118136613/214862478-89d14faa-38a6-4b4b-a634-e7c141d68fcd.png">

​

## Acceptance Criteria

- [ ] a heart icon is displayed at each entry on the words page
- [ ] clicking the heart icon marks the entry as liked/favorite (icon filled) and adds it to the favorite list
- [ ] a link with a heart icon is displayed on top of the words page
- [ ] clicking the heart link displays the favorite list

## Tasks

- [ ] add a button with the heart icon to the button component
- [ ] add the heart button to the listEntry
- [ ] create a state isLiked/isFavorite with an initially empty array
- [ ] write a handleLike function that adds or removes the entry from the state array when the button is clicked
- [ ] add a heart link to the words page 
- [ ] write a function that renders all liked entries from the state array in a list when the heart link is clicked
      ​

## Complexity

M
