### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#14]
## Value Proposition

**As a** User 
**I want to** have the possibility to search in my lists
**so that** I can find a certain word
​

## Description

![Screenshot 2023-01-30 at 2 53 07 PM](https://user-images.githubusercontent.com/118136613/215496482-ac1862ee-5ec4-4474-83c5-685bbdfe4b53.png)

## Acceptance Criteria

- [ ] the added and edited words are persistent
- [ ] an input field to search for a word is displayed on the home page and on the words page
- [ ] a list of matching words is displayed in the moment of typing in the input field
- [ ]  if the searched word is not found the user should see an info "not in your list"
- [ ] next to the input field a button "show entry"is displayed 
- [ ] if the searched  word is in the list clicking the button shows the entry of the searched word 
 
      ​

## Tasks

- [ ] change the globalState to localStorage
- [ ] create a search component with an input field and a button
- [ ] control the input to read the value of the input field and display the matching results
- [ ] write a submit function to conditionally render the list item or the not-found message
- [ ] implement the search component on the home page and on the words page
      ​

## Complexity

M

**Comment by marcterre** [comment]
Hey Astrid, i dont know what you mean with "if the word is found clicking the button shows the entry". Do you mean when i click the word i searched for shows the details of the word? Just describe the button more 🙂 The rest looks good

**Comment by RobinWitt** [comment]
looks good to me!
