### ISSUE TITLE
Store and fetch data in mongoDB 

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#16]
## Value Proposition

**As a** User  
**I want to** store the words in a database
**so that** I can access them at any time
​

## Description

All words and changes the user makes are saved in the MongoDB Cloud. Up to now the displayed lists are from a hard-coded data-object. Changes cannot be saved.
(no visual change)
​

​

## Acceptance Criteria

- [ ] the data is fetched from a MongoDB via API routing
- [ ] error handling and request methods are implemented
- [ ]  if the user has to wait for the response or the request fails, they get appropriate messages

## Tasks

- [ ] add a db folder; inside the folder add files for the necessary DB models and 'dbConnect' function
- [ ] create the connecting-string and store it in .env.local
- [ ] add API to pages, implement HTTP request methods
- [ ] implement error handling on the according pages to inform the user if the response is loading or the request has failed
​
## Complexity
L
