### ISSUE TITLE
speech synthesis

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#19]
## Value Proposition

**As a** User  
**I want to** hear how words are pronounced
**so that** I pronounce them correctly 
​

## Description

![Screenshot 2023-02-02 at 12 00 13 PM](https://user-images.githubusercontent.com/118136613/216307238-b1ee554a-0127-4b62-85e7-c30d3a9423f1.png)

## Acceptance Criteria

- [ ] a button to activate speech synthesis is displayed on each entry
- [ ] when the user clicks the button he hears the pronunciation of the word

      ​

## Tasks

- [ ] get familiar with the speech synthesis the browser offers
- [ ] write a handleSpeech function that enables speech synthesis for each word entry

     
## Complexity

L
