### ISSUE TITLE
Fetch Translation

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#2]
## Value Proposition

As a User
I would also like to be able to specify the language origin
so that it is displayed next to the word and its translation
​

## Description
<img width="679" alt="Screenshot 2023-01-23 at 4 24 17 PM" src="https://user-images.githubusercontent.com/118136613/214078322-bd1b51c4-b3f2-4122-ad53-753b306a9c52.png">

## Acceptance Criteria

- [ ] in the first input field you can enter the search word
- [ ] in the second input field you can enter the source language
- [ ] in the third input filed the translation can be entered
- [ ] a submit-button is displayed below which submits the input (FormData)
- [ ] submitting the form adds a list-entry to the list
- [ ] the entry is only added to the list if it is not already in the list
- [ ] the user gets a message if the entry is already in the list
- [ ] in the list-entry the entered word, the translation and the source language is shown
- [ ] submitting the form resets the fields

      ​

## Tasks

- [ ] create another input field to take the source language  
- [ ] adapt the handleSubmit function for the list entry so that it is also submitting the source language
- [ ] add the source language to the list entry 
- [ ] add a success and failure message
- [ ] conditionally render the message for the user
 ​

## Complexity
S

**Comment by RobinWitt** [comment]
Good structure overall. Although for me, it is not clear at what point the detection and display of the language will be happening, is it an 'onChange' function that works while you type the word? 

Also, since your translation is now provided by the API, you should decide whether you want to keep an optional second input field in case there is no available translation or change the input field to a 'text' element. (your second to last task isn't descriptive enough on that)

**Comment by AstridOttmann** [comment]
You are right! 
Point1: The problem is that I don't know which API I will use and how it will exactly behave. 
Point2: The option with a second input field if the language is not detected I will implement in the next step, when I know the API. So I changed to text fields.

**Comment by RobinWitt** [comment]
Thanks for clarifying looks good to me then!

**Comment by AstridOttmann** [comment]
Clearified the search-submit!

**Comment by AstridOttmann** [comment]
Please have a look again. I made some changes and decided to fake the fetch at this early time in the project because of a limited number of monthly fetches

**Comment by RobinWitt** [comment]
That User Story is now very descriptive! Good job.

**Comment by RobinWitt** [comment]
I think you should not mention the input field again though, since you already created it in your first User Story.

**Comment by AstridOttmann** [comment]
I mentioned it  again because now it is a search field. In my #1 story the user was filling in both fields (there was no search)

**Comment by RobinWitt** [comment]
Oh, my mistake! Makes totally sense then :D

**Comment by doemser** [comment]
Well done! :) The value proposition of your user-story is just a bit hard to read. 

If you find it hard to write the user-stories in English, then that's normal, it's the same for me. 
The easiest way, and I often do it, is to use DeepL as a translator, see how well he does it:
![Screenshot 2023-01-23 at 16 23 07](https://user-images.githubusercontent.com/93415777/214078299-2f27ce60-e9a7-48b4-9735-7980b93ec728.png)

**Comment by AstridOttmann** [comment]
Thank you!
But I changed the story again, because my code is already at the point where the message is implemented. I hope I don't have to delete it again.

**Comment by doemser** [comment]
Your code should actually be at the level of the first user-story for your PR. One user story, one PR. The change to the user-story seems a bit "careless" and the user-story needs to be completely re-evaluated. Rather let your code depend on what the story wants, not the other way around. 

So keep the user-story as it was and check off two user-stories with one PR instead of jumbling it up, you won't do yourself any favors.
