### ISSUE TITLE
Refactoring SpeechSynthesis-function

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#22]
## Value Proposition

**As a** User
**I want to** have the possibility to choose the voice of the speech synthesis
**so that** I hear a native speaker and learn the pronunciation correctly 
​

## Description

While implementing the speechSynthesis-function it turned out, that there are some weaknesses to be fixed: 
- newly entered words get automatically the default voice (US-english) 
- that delivers a wrong pronunciation for other languages, i. e. Dutch
- and it can't be changed

![Screenshot 2023-02-07 at 10 40 15 AM](https://user-images.githubusercontent.com/118136613/217208155-7073fdc8-063e-4cef-8fa2-2e75f4ba791a.png)

To solve this, a voice-selector has to be added. 
The speechSynthesis-module is moved to the word entry page, so that the list entries are not so cluttered.

​

## Acceptance Criteria

- [ ] a dropdown menu to select a voice is displayed on the words entry page
- [ ] a submit button to set the chosen voice is displayed on the words entry page
- [ ]  a button to activate speech synthesis is displayed on each entry
- [ ] when the user clicks the button he hears the pronunciation of the word in the chosen voice
      ​

## Tasks

- [ ] create a speechSynthesis component
- [ ] create a speechSynthesisVoiceSelector component
- [ ] write a handleSpeech function that enables speech synthesis for each word entry
- [ ] write a custom hook to collect all voices and display them in the speechSynthesisVoiceSelector 
- [ ] make the voices the browser offers available on the word entry page
- [ ] write a submit function that sets the chosen voice and pass it to the handleSpeech function

      ​

## Complexity

M
