### ISSUE TITLE
Implement API-translation

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#23]
## Value Proposition

**As a** User
**I want to** enter a word I don't know 
**so that** I get the translation
​

## Description
![Screenshot 2023-02-07 at 1 12 33 PM](https://user-images.githubusercontent.com/118136613/217241852-cb314424-a9eb-4b79-8340-313fd30e3ff0.png)

​

## Acceptance Criteria

- [ ] an input field for the word that is to be translated is displayed on the homepage
- [ ] an input field for the target language is displayed on the homepage
- [ ] a translate button is displayed on the homepage
- [ ] clicking the button delivers the translation of the entered word in the target language and the detected language
- [ ] two buttons 'save' and 'discard' are displayed below the translation to either save  the result as a word entry or discard it
- [ ] clicking one of the buttons resets the input fields
      ​

## Tasks

- [ ] create a form component for the translation feature
- [ ] write a handleSubmit function
- [ ] get familiar with the translation API
- [ ] create an authentication key to access the API.
- [ ] create an api/words folder
- [ ] inside the folder create a file
- [ ] inside the file write a function to fetch the data from the API and display the result
- [ ] write a function to either save or discard the result and reset the form
      ​

## Complexity
L

**Comment by HosseinKrouna** [comment]
Hi Astrid,

it's okay for me
👍

**Comment by HosseinKrouna** [comment]
Hi Astrid, 
so far it looks very good. 
As a user experience, I think it would be great if, after the translation, the word you just entered could also be seen somewhere before I save. e.g. when I translate it into japanese and go away for a while and come back and just see the word in japanese and don't remember what it was before.



"two buttons 'save' and 'discard' are displayed below the translation to either save the result as a word entry or discard it"
"clicking one of the buttons resets the input fields"

I can't get this feateur

**Comment by AstridOttmann** [comment]
Hi Hossein, 
thank you! You are totally right in both points. 
I tried it to display the entered word, but it did not work and up to now I could not find a solution. 
The same is with saving the result as entry. 
I'll go on trying to figure it out.

**Comment by AstridOttmann** [comment]
One problem is solved, the word AND the translation are displayed now!

**Comment by AstridOttmann** [comment]
Now you can also save or discard the entry. :-)
