### ISSUE TITLE
Learning function

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#24]
## Value Proposition

**As a** User
**I want to** have a learning function
**so that** I can practice the language  
​

## Description

![Screenshot 2023-02-07 at 2 54 12 PM](https://user-images.githubusercontent.com/118136613/217264289-52b88b99-b649-4fed-bdba-b2ce4398036f.png)

## Acceptance Criteria

- [ ] a button to get a random word is displayed on the words page
- [ ] clicking the button selects a random word from the list
- [ ] a show answer button is displayed below
- [ ] clicking the button shows the answer

      ​

## Tasks

- [ ] create a learning component and implement it on the words page
- [ ] write a function to get a random word from the list of words
- [ ] create a button and write a function to toggle the answer
      ​

## Complexity

S-M
