### ISSUE TITLE
Styling landing page

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#27]
## Value Proposition

**As a** User 
**I want to** I want to have a clear and simple UI
**so that**  it's easier to understand the app.
​
## Description
![Screenshot 2023-02-11 at 8 10 06 PM](https://user-images.githubusercontent.com/118136613/218276688-97f34cbc-7736-496d-a422-8512a805498c.png)
​
## Acceptance Criteria

- [ ] display styled buttons
- [ ] display styled header 
- [ ] display styled navigation
      ​

## Tasks

- [ ] add a basic styling to the root/body
- [ ] add styling to the buttons
- [ ] add styling to the header
- [ ] add styling to the main navigation
- [ ] if necessary add fonts

      ​

## Complexity
S-M

**Comment by gulfemakkaya** [comment]
Looks good. And I like the idea of a simple design since it´s a language app 👍🏻
