### ISSUE TITLE
Layout pages

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#29]
## Value Proposition

**As a** User
**I want to**  have a a clear and simple UI on all pages
**so that**  I can easily navigate through my app
​

## Description

Layout of the pages
​

## Acceptance Criteria

- [ ] the layout of the pages is consistent
​

## Tasks

- [ ] create the layout of the pages
- [ ] integrate the components in the layout of the pages
- [ ] ...
      ​

## Complexity

M
