### ISSUE TITLE
Save or Discard

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#3]
## Value Proposition

As a User 
I want to have my lists on an extra page
so that I have a better overview 
​

## Description

<img width="713" alt="Screenshot 2023-01-23 at 4 37 11 PM" src="https://user-images.githubusercontent.com/118136613/214081652-bfb8b0af-c685-48dd-b34e-e521f1566dd9.png">

​

## Acceptance Criteria

- [ ] the words-page displays all saved entries as a list
- [ ] a navbar is displayed at the bottom of each page
- [ ] tne navbar has a home button and a words button to navigate between the two sides
      ​

## Tasks

- [ ] create a new folder 'words' in pages containing and index.js-file
- [ ] make the state of the list-array global
- [ ] display the list component on the newly implemented page
- [ ] create a navbar component with two links to switch between the two pages
      ​

## Complexity

M

**Comment by RobinWitt** [comment]
Hi Astrid, you might need one of these additional functions for your translation element to work:
Option A: Submit Button (to submit input data to the API) to see your translated word before deciding what to do with it.
Option B: Controlled Input that gives you live results.

**Comment by AstridOttmann** [comment]
Good advice!
I change #2 to use option A (submit: Object.fromEntries)
