### ISSUE TITLE
Delete-Function

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#4]
## Value Proposition

**As a** User 
**I want to** be able to delete words from my list  
**so that** I can sort out my list any time   
​

## Description
​
<img width="704" alt="Screenshot 2023-01-20 at 6 51 40 PM" src="https://user-images.githubusercontent.com/118136613/213772097-b0850d8b-32bc-4993-a49c-034d6e7236f0.png">

## Acceptance Criteria

- [ ] a delete button is shown for every list entry
- [ ] If the delete button is clicked, the list entry is removed from the list

      ​

## Tasks

- [ ] create a delete button
- [ ] write a handleDelete function, which removes the list entry from the list
      ​

## Complexity

S

**Comment by JoergWolff** [comment]
I hope i can help.
Why can I see the app twice in the description?
Otherwise it looks good.

**Comment by AstridOttmann** [comment]
The right wireframe shows the content after list entry 2 was deleted. But you're right, it's a little bit confusing, because both lists have the same length, so it's not obvious. I changed it ;-)

**Comment by RobinWitt** [comment]
looks good to me!
