### ISSUE TITLE
Manage to store multiple languages

### ISSUE THREAD

**Issue by AstridOttmann** [AstridOttmann/capstone-project#5]
## Value Proposition

**As a** user
**I want to** have a separate list for each language 
**so that** I can store multiple languages well structured
​

## Description

<img width="698" alt="Screenshot 2023-01-20 at 8 45 04 PM" src="https://user-images.githubusercontent.com/118136613/213792008-dbbbb3eb-1ec6-4846-9623-209b1f4d3ba5.png">

​

## Acceptance Criteria

- [ ] a second navbar (language navigation) to navigate through the different languages is displayed below the header
- [ ]  the language navigation contains one button for each language that is already in the list
- [ ] if the detected language doesn't already exist in the list, a new button and a new list will be automatically created when saving the translated word
- [ ] the chosen language is highlighted in the language navigation
- [ ] only the list entries of the chosen language are displayed on the page 
      ​

## Tasks

- [ ] create a language navigation component that renders one button for each language and shows the chosen language button highlighted
- [ ]  refactor the language navigation component to add a button and a list when the detected language doesn't already exists in the navigation
- [ ] write a function that filters the list of all words and only displays the list of the chosen language 

      ​

## Complexity

M-L

**Comment by RobinWitt** [comment]
Hi Astrid, that is a nice feature for your app!
I like the User Story and the wording.
One suggestion: To prevent confusion, maybe you should use different descriptions for your Navigation on the bottom and your other navigation components.
('Language Selection' ?)

**Comment by AstridOttmann** [comment]
Thank you, you're right. i'll change it.

**Comment by RobinWitt** [comment]
approved!
